### ISSUE TITLE
Sex-ENUM: "UNKNOWN_SEX" occurs twice

### ISSUE THREAD

**Issue by domibln** [phenopackets/phenopacket-validator#29]
I suppose this is an error (`phenopacket-general-schema.json`):

```
          "sex": {
            "enum": ["UNKNOWN_SEX", "FEMALE", "MALE", "UNKNOWN_SEX"]
          },
```

**Comment by julesjacobsen** [comment]
HI @domibln, thanks for your feedback. Sorry, this validator project has been merged with the phenopacket-tools. If you checkout the develop branch - https://github.com/phenopackets/phenopacket-tools/tree/develop. This is not the case there:

https://github.com/phenopackets/phenopacket-tools/blob/fc865fcb692000add853005f26a0b5a3aeec05f4/phenotools-validator-jsonschema/src/main/resources/schema/phenopacket-schema-2-0.json#L37-L39

Sorry again, this is still all a bit work in progress!
